shared-property: from develop branch
logging:
  file: naps-applicant-api-1.log
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
privacy:
  states: 
    $include: https://github.com/yupingxu/config-repo/blob/develop/configClient.yml
