test: dev
test2: dev2
shared-property: from develop branch dev profile
logging:
  file: naps-applicant-api-dev.log
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
privacy:
  states: $include: client1-dev.yml
